[package]
name = "postgres_money"
version = "0.1.0"
authors = ["Thomas Brigham <thomas@thomasbrigham.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
